### PR TITLE
Remove gocov

### PR DESCRIPTION
**Pull request by mattn**
I'm having plan to remove gocov feature from goveralls. golang.org/x/cover have ParseCoveerFile so no need to use gocov at least. And gocov is slow on windows because it install all dependencies into test directoy. So I decided to remove gocov feature.

### CODE REVIEW

**Comment by arvenil** [comment]
Hi,

I was using gocov reports and I don't understand what happen here? Did you completely dropped the support of parsing and sending `coverage.json` generated by gocov? Or is there other method to parse existing `coverage.json`?

**Comment by mattn** [comment]
@arvenil Sorry, I no longer couldn't provide same qualities for all-platform.

**Comment by arvenil** [comment]
So it got totally removed? What's then a suggested way to generate coverage for multiple packages (subpackages/whole project) and sending it to goveralls?

Previously I was able to do:
```
gocov test -covermode=atomic ./... > $CIRCLE_ARTIFACTS/coverage.json
goveralls -gocovdata=$CIRCLE_ARTIFACTS/coverage.json -service=circle-ci -repotoken=$COVERALLS_TOKEN
```

Now I'm not able to generate coverage for the whole project:/ I can generate coverage for only one package:/

Why it was removed in the first place? Was something not working?

**Comment by mattn** [comment]
One of solution

https://github.com/mattn/goveralls/issues/68#issuecomment-198573259

**Comment by arvenil** [comment]
So, now I need to install BDD framework (ginkgo) just to be able generate multiple coverprofiles and then I need to install gover (unmaintained since 2 years with bug in readme) just to merge them in one report... ok, anyway, thanks for info.

**Pull request merged**
