### PR TITLE
Introduce a new option -uploadsource

### PR DESCRIPTION
**Pull request by gdm85**
This PR introduces a new option `-uploadsource=true` which allows to disable uploading source code to coveralls.io.

Additionally it fixes panics due to local files having less lines than what is reported on the coverage profile since reading the count of lines from the source is not needed anymore (example: #86).

Existing behaviour is preserved because the default value is `true`.

Other changes:
* return error instead of using `log.Fatal` in a couple functions

### CODE REVIEW

**Comment by gdm85** [comment]
Any suggestions to increase the coverage by 0.2%? I am not sure I understand why it has decreased either.

**Comment by nbaztec** [comment]
Could be that it was never covered before and you touched those lines and they are still not covered, so marked uncovered. Had some situations like that before. 
And easy debug/print on the test `toSF` should tell us that

**Comment by gdm85** [comment]
I do not think it should be a blocker for this PR or the other one, which has the same issue (#181); coverage seems already pretty bad on its own (~11.9%). If we want to increase coverage of this project as a whole it should be addressed on a separate PR.

So please review it as usual, thanks!

**Review by shogo82148 — APPROVED** [review]
LGTM 👍

**Comment by mattn** [comment]
Feel free to merge. Thanks.

**Pull request merged**
