### PR TITLE
Miscellaneous fixes (mostly for non-CI invocations)

### PR DESCRIPTION
**Pull request by albertito**
Hi!

I run goveralls outside the existing CIs, and noticed two issues which are fixed by these two (independent) patches.

I hope these these are ok to you, please let me know if you have any questions or comments!

Thanks!
        Alberto

### CODE REVIEW

**Comment by mattn** [comment]
What errors did you get?

**Comment by albertito** [comment]
Without the service name, coveralls always assigned the upload to an old build, like a new job for an old build, and did not reflect the state of the repository or current coverage.

For example, this was not the 8th job attempted for that commit, but a much later commit that got wrongly assigned: https://coveralls.io/jobs/44329219

This affects manual uploads, and uploads from CIs unknowns to goveralls. 


The "git remote" commit is a privacy change, I was not getting any errors but it's also not useful, and leaks potentially private information to a third party.

Let me know if you have any more questions!

**Comment by mattn** [comment]
You are right. Thanks for your explaining.

**Comment by mattn** [comment]
Thanks.

**Comment by rensdad1** [comment]
Little late on the fucking info but used all I had helping  so.eone and screen only works on the one that don't work I can't fucking win

**Pull request merged**
