### PR TITLE
Add jobId field to support build for each job in non-supported ci's

### PR DESCRIPTION
**Pull request by rohitsakala**

### CODE REVIEW

**Comment by mattn** [comment]
What the use-case?

**Comment by rohitsakala** [comment]
> What the use-case?

Hi Mattn,

For non-supported ci's,  such as concourse, a job submitted is not being converted into a new build. This happens for supported ci's such as travis etc. So, I have added a parameter which can be given by the user to trigger a new build. Let me know your thoughts on this ?

Thanks,
Svk Rohit

**Comment by mattn** [comment]
Travis is failing

**Comment by shogo82148** [comment]
custom job id is now supported by https://github.com/mattn/goveralls/pull/145.
enjoy!

**Pull request closed without merging**
